/*
 * Copyright (c) 2006-2021, RT-Thread Development Team
 * SPDX-License-Identifier: Apache-2.0
 *
 * Change Logs:
 * Date           Author                 Notes
 * 2025-11-08     OwensMegan7913         the first version, generated by Copilot
 * 2025-11-08     Copilot                Fixed bugs and improved robustness
 */
#ifndef APPLICATIONS_ADS131M08_APP_H_
#define APPLICATIONS_ADS131M08_APP_H_

#include <rtthread.h>
#include "ads131m08_hal.h"
#include "../services/digital_filtering.h"
#include "../tasks/config_thread.h"

// ADC参考电压和满量程码值 (24位ADC)
#define ADC_VREF                1.2f
#define ADC_FULL_SCALE_CODE     8388607.0f
// S1: 应变灵敏度 (单位: V/uε)
#define S1 (0.050f / 3000.0f)
// ε0: 应变零点漂移 (单位: uε)
#define STRAIN_ZERO (0.0f)
// S2: 加速度灵敏度 (单位: V/mg)
#define S2 (2.5f / 2000.0f)
// a0: 加速度零点漂移 (单位: mg)
#define A_ZERO (2.5f)


extern rt_sem_t tim3_sem;
extern rt_hwtimerval_t tim3_timeout_s;


int tim3_init(void);
float ads131m08_convert_to_voltage_uv(rt_int32_t raw_value, rt_uint16_t gain);
float convert_to_strain_ue(float input_voltage_v);
float convert_to_acceleration_mg(float input_voltage_v);


#endif /* APPLICATIONS_ADS131M08_APP_H_ */
