/*
 * Copyright (c) 2006-2021, RT-Thread Development Team
 * SPDX-License-Identifier: Apache-2.0
 *
 * Change Logs:
 * Date           Author                 Notes
 * 2025-11-09     OwensMegan7913         the first version, generated by Copilot
 * 2025-11-09     Copilot                Refactored to support robust runtime configuration
 */
#ifndef APPLICATIONS_ADS131M08_HAL_H_
#define APPLICATIONS_ADS131M08_HAL_H_

#include <rtthread.h>

/* ================== 1. 引脚和设备名称定义 ================== */
#define ADC_SPI_DEVICE_NAME     "spi20"

/* ================== 5. HAL层错误码定义 ================== */
#define ADC_EOK                  0   // 成功
#define ADC_ERR_DEVICE_FIND     -1   // 找不到SPI设备
#define ADC_ERR_DEVICE_OPEN     -2   // 打开设备失败
#define ADC_ERR_DRDY_TIMEOUT    -3   // 等待DRDY高电平超时
#define ADC_ERR_REG_WRITE_CLK   -4   // 写CLOCK寄存器失败
#define ADC_ERR_REG_WRITE_MODE  -5   // 写MODE寄存器失败
#define ADC_ERR_SET_GAIN        -6   // 设置增益失败
#define ADC_ERR_REG_ENABLE_CH   -7   // 启用通道失败

/* ================== 2. ADS131M08寄存器地址 ================== */
#define STATUS_ADDR             0x01


#define CLOCK_ADDR              0x03
#define ALL_CH_ENABLE_MASK      0xFF00
#define OSR_1024_MASK           0x000C
#define OSR_4096_MASK           0x0014 //在F_clkin=8196khz时，对应1ksps
#define PWR_HR_MASK             0x0002

#define MODE_ADDR               0x02
#define CRC_EN_MASK             0x1000
#define RESET_MASK              0x0400
#define WLENGTH_24_MASK         0x0200
#define WLENGTH_32_SIGN_EXTEND_MASK 0x0300
#define DRDY_FMT_PULSE_MASK     0x0001

#define GAIN1_ADDR              0x04

#define GAIN2_ADDR              0x05


/* ================== 4. HAL层配置 ================== */
#define CLK_SEL_8_192_MHZ       1
#define CLK_SEL_4_096_MHZ       2
#define CLK_SEL_2_048_MHZ       3
#define ADC_CLK_SELECTION       CLK_SEL_8_192_MHZ

#define ADC_FRAME_WORD_COUNT    10
#define ADC_NUM_CHANNELS        8

extern rt_sem_t drdy_sem;

/* ================== 5. 函数声明 ================== */
rt_err_t ads131m08_init(void);
rt_err_t ads131m08_read_data_frame(rt_int32_t *buffer, rt_bool_t is_first_read);
rt_bool_t adcRegisterWrite(rt_uint8_t addr, rt_uint16_t data,rt_uint8_t word_length);
rt_bool_t adcRegisterRead(rt_uint8_t addr, rt_uint16_t *data,rt_uint8_t word_length);
rt_err_t ads131m08_set_gain(rt_uint16_t gain);
rt_err_t ads131m08_enable_cannel(rt_uint8_t channel_code);
#endif /* APPLICATIONS_ADS131M08_HAL_H_ */
